### ISSUE TITLE
9.6 Update Errors

### ISSUE THREAD

**Issue by Dave247** [TheKye/TheGreatCollective#6]
To preface, all of the mods were downloaded from Mod.io.

NyElectricts, WoodenBraces, WireFences & ConvenorBelts will all cause the server to crash with the following error error,
```
[21:49:44.354] [1] [Error] [Eco] Failed to start the server. Exception was Exception: Exception
Message:C:\Users\david\Desktop\EcoServerPC_v0.9.6.1-beta\Mods\UserCode\ConveyorBelts\ConveyorBeltObject.cs(26,60): error CS0246: The type or namespace name 'IChatCommandHandler' could not be found (are you missing a using directive or an assembly reference?)
Source:Eco.ModKit

System.Exception: C:\Users\david\Desktop\EcoServerPC_v0.9.6.1-beta\Mods\UserCode\ConveyorBelts\ConveyorBeltObject.cs(26,60): error CS0246: The type or namespace name 'IChatCommandHandler' could not be found (are you missing a using directive or an assembly reference?)
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
```
The SteamFrontLoader will load with the server but isn't placeable in game, so it too likely suffers from the same problem.

PaperMillingExpanded causes the following error on server launch
```
[22:11:09.510] [22] [ Warn] [Eco] Failed to get derived types for 'Eco.World.Blocks.Block' in assembly 'PaperMillingExpanded, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (usually safe to ignore for third party assembly). Error message: Unable to load one or more of the requested types.

 
[22:11:09.543] [4] [ Info] [Eco] Server Initialization                             ... Finished in 20.890 sec
 
[22:11:09.551] [8] [Error] [Eco] Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.

Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionUtils.<>c.<GetFilteredAssemblyTypes>b__10_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.IO.FileNotFoundException: 
File name: 'Eco.EM.Framework, Version=3.1.6.0, Culture=neutral, PublicKeyToken=null'
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
 
[22:11:14.559] [8] [ Info] [Eco] Shutdown finished
```

Dynamite being the oldest updated mod, caused the following error on server launch,
```
[22:12:09.887] [17] [Error] [Eco] Failed to start the server. Exception was Exception: TypeLoadException
Message:
Source:System.Private.CoreLib

System.TypeLoadException
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at Eco.Gameplay.Items.TagManager.Initialize()
   at Eco.ModKit.ModDataSync..ctor()
   at Eco.ModKit.ModKitPlugin.<LoadModsDataAsync>b__32_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Eco.ModKit.ModKitPlugin.LoadModsDataAsync()
Outer Exceptions:
One or more errors occurred. ()
 
[22:12:14.899] [17] [ Info] [Eco] Shutdown finished
```

Meanwhile both the ModernSolarPannel & SeedBarrel suffer the same problem as in #5, where while the icon asset is visible, the physical word asset is not, as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/10183015/188314056-1c9c33d2-d601-4d50-a38c-1696e6b227db.png)

Luckypickaxes while it does seems to work, suffers from the same animation issue as the BigShovelMod with https://github.com/StrangeLoopGames/Eco/pull/11483, while also causing the following notification to appear in the chatbox due to the sound not playing when using the pickaxe, `Failed to handle RPC method SoundActionRPC`

**Comment by TheKye** [comment]
there is a 9.6 branch that needs to be polished then released then a bunch of these issues should be fixed :)

**Comment by Dave247** [comment]
Ah I had a look at the main branch but didn't think to check for other branches. Good to hear though! I know these mods are a more minor thing so no rush, with the start of a new cycle I've just been going through everything to see what still works and what doesn't.

**Comment by destotelhorus** [comment]
Is there a description somewhere what needs to be done with the assets? maybe I can help out and fix some of those?!
